language: python
python:
  - "3.7.4"
  - "3.8.4"
before_install:
  - sudo apt-get -y install r-base
install:
  - pip install .
  - pip install pytest pytest-cov coveralls
script:
  - pytest --cov=kmerdb/
after_success:
  - coveralls
