language: python
python:
  - "3.12.2"
before_install:
  - sudo apt-get -y install r-base
install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install pytest pytest-cov coveralls
script:
  - pytest --cov=kmerdb/
after_success:
  - coveralls
